plugins:
  localPath: '../../'
  modules:
    - serverless-plugin-kong

service: example

provider:
  name: aws
  runtime: nodejs18.x

functions:
  hello:
    handler: handler.hello
    events:
      - kong:
          route:
            methods:
              - GET
            paths:
              - /
            protocols:
              - http
          plugins:
            - name: basic-auth
              enabled: true
              config:
                hide_credentials: true

custom:
  kong:
    admin_api_url: http://localhost:8001
    virtual_service:
      name: lambda-BFF-service
      url: http://localhost:8001
      base_path: /bff
    tags:
      - serverless-plugin-kong
      - lambda-BFF-virtual-service
    lambda:
      config:
        aws_key: ${env:AWS_ACCESS_KEY_ID, 'asdf'}
        aws_secret: ${env:AWS_SECRET_ACCESS_KEY, 'asdf'}